# Generated by Django 3.1.2 on 2020-10-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=10)),
                ('DishBrief', models.CharField(max_length=200, null=True)),
                ('DishPic', models.ImageField(null=True, upload_to='')),
                ('DishScore', models.IntegerField(null=True)),
                ('DishPrice', models.FloatField(max_length=5)),
                ('DishSell', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=50)),
                ('TStatus', models.BooleanField()),
                ('OrderTime', models.TimeField()),
                ('CloseTime', models.TimeField(null=True)),
                ('Cost', models.FloatField(max_length=5)),
                ('Canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trytest.canteen')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10, null=True)),
                ('Password', models.CharField(max_length=20)),
                ('Money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentScore', models.IntegerField(null=True)),
                ('Dishes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trytest.dishes')),
                ('Trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trytest.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=200)),
                ('Reply', models.CharField(max_length=200, null=True)),
                ('Trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trytest.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trytest.user'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(null=True, upload_to='')),
                ('Introduction', models.CharField(max_length=200)),
                ('PName', models.CharField(max_length=20)),
                ('Support', models.IntegerField(null=True)),
                ('PStatus', models.BooleanField()),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trytest.user')),
            ],
        ),
    ]
